- name: Spawn OpenStack Instances
  os_server:
    name: "{{ item.key }}"
    state: present
    image: "{{ item.value.image }}"
    key_name: root-OpenStack-master
    timeout: 2000
    flavor: "{{ item.value.flavor }}"
    auto_ip: no
    nics: "{{ 'port-name=' + item.value.port | join(',port-name=') }}"
    security_groups: "{{ item.value.security_group | default('default') }}"
    meta: "{{ item.value.tags }}"
    boot_from_volume: "{{ item.value.persistent }}"
    volume_size: "{{ item.value.volume_size | default(omit) }}"
    terminate_volume: yes
  with_dict: "{{ servers_static }}"
