---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Make sure elk security group is present
    os_security_group:
      state: present
      name: elk
      description: Security group for elk machine
  
  - name: Make sure ICMP is allowed
    os_security_group_rule:
      security_group: elk
      protocol: icmp
      remote_ip_prefix: 0.0.0.0/0
    
  - name: Make sure ssh is allowed
    os_security_group_rule:
      security_group: elk
      protocol: tcp
      port_range_min: 22
      port_range_max: 22
      remote_ip_prefix: 0.0.0.0/0

  - name: Make sure port 80 is allowed
    os_security_group_rule:
      security_group: elk
      protocol: tcp
      port_range_min: 80
      port_range_max: 80
      remote_ip_prefix: 0.0.0.0/0
